# Change these first
owner: eAimodotes # Your GitHub organization or username, where this repository lives
repo: aimodotes-status # The name of this repository

sites:
  - name: e-Αιμοδότες
    url: https://e-aimodotes.gr/
  - name: e-Αιμοδότες για νοσοκομεία
    url: $URL_BACKEND
  - name: e-Αιμοδότες API (Mobile Apps)
    url: https://api.e-aimodotes.gr/metrics/uptime/
  - name: e-Αιμοδότες (Κράτηση Ραντεβού για Αιμοδοσία)
    url: https://bookings.e-aimodotes.gr/
  - name: e-Αιμοδότες ΑμΚΕ
    url: https://aimodotes.org/
  - name: Μητρώο εθελοντών (ΑμΚΕ)
    url: $URL_VOLUNTEERS
  - name: Στατιστικά εφαρμογών
    url: $URL_STATISTIKA
  - name: Διακομιστής Ίρις (Δημοκρίτειο Πανεπιστήμιο Θράκης)
    url: $SERVER_IRIS
  - name: Διακομιστής Ερμής (Εθνικό Δίκτυο Υποδομών Τεχνολογίας και Έρευνας)
    url: $SERVER_ERMIS
  - name: Διακομιστής Αρετή (Cloudflare)
    url: $SERVER_ARETI

status-website:
  cname: status.aimodotes.org
 # introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  logoUrl: https://e-aimodotes.gr/assets/img/transpar.png
  favicon: https://e-aimodotes.gr/assets/img/transpar.png
  name: Κατάσταση Συστημάτων
  introMessage: "Σε αυτή τη σελίδα μπορείς να παρακολουθείς την κατάσταση των συστημάτων του e-Αιμοδότες. Τα στατιστικά για τα συστήματα παρέχονται για ενημερωτικούς σκοπούς."
  customHeadHtml: "<!-- Matomo -->
<script>
  var _paq = window._paq = window._paq || [];
  /* tracker methods like 'setCustomDimension' should be called before "trackPageView" */
  _paq.push(['trackPageView']);
  _paq.push(['enableLinkTracking']);
  (function() {
    var u='https://analytics.aimodotes.org/';
    _paq.push(['setTrackerUrl', u+'matomo.php']);
    _paq.push(['setSiteId', '9']);
    var d=document, g=d.createElement('script'), s=d.getElementsByTagName('script')[0];
    g.async=true; g.src=u+'matomo.js'; s.parentNode.insertBefore(g,s);
  })();
</script>
<!-- End Matomo Code -->"

  navbar:
    - title: Status
      href: /

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
